name: CI Pipeline

on:
  push:
    branches:
      - main  # Gatilho para commits na branch principal
  pull_request:
    branches:
      - main  # Gatilho para PRs direcionados à branch principal
  workflow_dispatch:  # Gatilho para execução manual, útil para webhooks do CMS
  schedule:
    - cron: '0 0 * * 1-5'  # Gatilho para execução às 00:00 de segunda a sexta-feira

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21'

      - name: Install dependencies
        run: npm install
        working-directory: miniprojetoantoniosousa

      - name: Run ESLint
        run: npx eslint . --ext .js,.jsx,.ts,.tsx
        working-directory: miniprojetoantoniosousa

      - name: Check code formatting
        run: npx prettier --check .
        working-directory: miniprojetoantoniosousa

      - name: Run Unit Tests
        run: npx jest --coverage --passWithNoTests
        working-directory: miniprojetoantoniosousa

      - name: Build Project
        run: npx next build
        working-directory: miniprojetoantoniosousa
        env: 
          CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
          CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}

  deploy:
    needs: build
    if: github.ref == 'refs/heads/main'  # Apenas executa o deploy na branch principal
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21'

      - name: Deploy to Vercel
        run: npx vercel --prod --token ${{ secrets.VERCEL_TOKEN }}
        working-directory: miniprojetoantoniosousa
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
