name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21'

      - name: Install dependencies
        run: npm install
        working-directory: miniprojetoantoniosousa  # Apenas o diretório do projeto Next.js

      - name: Run ESLint
        run: npx eslint .  # Removendo --ext
        working-directory: miniprojetoantoniosousa

      - name: Check code formatting
        run: npx prettier --check .
        working-directory: miniprojetoantoniosousa

      - name: Run Unit Tests
        run: npx jest --coverage --passWithNoTests
        working-directory: miniprojetoantoniosousa

      - name: Build Project
        run: npx next build
        working-directory: miniprojetoantoniosousa
        env: 
          CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
          CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}

  deploy:
    needs: build  #  que o build conclua antes do deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21'

      - name: Deploy to Vercel
        run: npx vercel --prod --token ${{ secrets.VERCEL_TOKEN }}
        working-directory: miniprojetoantoniosousa  # Garantir que deploy use o mesmo caminho do 
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
